name: Snyk Infrastructure as Code and GitHub Security example
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    #Configure AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
    
      # Scan Terraform Plan
    - name: Build TF Plan
      run: |
        terraform init
        terraform plan -out tf.plan 
        terraform show -json tf.plan > tf-plan.json
     
      # Build Custom Rule
    - name: Build Custom Rules
      id: opa
      uses: aserto-dev/opa-build-action@main
      with:
        source: .
        target: ./custom.tar.gz
        options: -t wasm -e "main/deny"
        
    - name: Run Snyk to check Terraform configuration file for issues
      continue-on-error: true
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: .
        command: test tf-plan.json --scan=planned-values --rules=custom.tar.gz --sarif-file-output=snyk.sarif
