name: Snyk Infrastructure as Code and GitHub Security example
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
  
    - name: Build TF Plan
      run: |
        terraform init
        terraform plan -out tf.plan 
        terraform show -json tf.plan > tf-plan.json
            
    - name: Run Snyk IaC
      id: snyk
      continue-on-error: true
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test tf-plan.json --scan=planned-values --rules=bundle.tar.gz --sarif-file-output=snyk.sarif
     
